[package]
name = "h264_nal_unit_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12" 
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3.31", default-features = false }
warp = "0.3.7"
