[package]
name = "h264_nal_unit_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.16"
futures = { version = "0.3", default-features = false }
warp = "0.3.7"
